In [1]:
import os
import sys
import pandas as pd

# Get the directory of the current notebook
notebook_dir = os.path.dirname(os.path.abspath("__file__"))

# Add the parent directory to the system path
storage_path = os.path.abspath(notebook_dir + "/../../cache/parquet/base/drives.parquet")

drives_df = pd.read_parquet(storage_path).sort_values(
    by=["season", "week"], ascending=False
)

pd.set_option('display.max_rows', 500)

drives_df

,season,week,gameId,position,teamDisplay,homeScore,awayScore,winning,winningChange,startTime,stopTime,startYards,stopYards,rushes,passes,points,turnover,plays
55716,2024,18,401671826,1,HOU,0,7,HOU,True,0,437,69,0,6,5,7,False,"[{'type': 'k', 'distance': 34, 'result': 'M.Wr..."
55717,2024,18,401671826,2,TEN,0,7,HOU,False,437,567,33,35,2,1,0,False,"[{'type': 'k', 'distance': -32, 'result': 'K.F..."
55718,2024,18,401671826,3,HOU,0,7,HOU,False,567,800,83,64,1,4,0,False,"[{'type': 'pass incompletion', 'distance': 0, ..."
55719,2024,18,401671826,4,TEN,0,7,HOU,False,800,953,25,42,3,1,0,False,"[{'type': 'rush', 'distance': 4, 'result': '(S..."
55720,2024,18,401671826,5,HOU,0,13,HOU,False,953,965,92,0,0,1,6,False,"[{'type': 'rec', 'distance': -92, 'result': 'D..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2015,1,400791600,15,SF,17,3,SF,False,2717,3030,20,100,5,4,7,False,"[{'type': 'k', 'distance': -45, 'result': 'B.W..."
348,2015,1,400791600,16,MIN,17,3,SF,False,3030,3098,80,67,0,2,0,True,"[{'type': 'k', 'distance': 32, 'result': 'B.Pi..."
349,2015,1,400791600,17,SF,20,3,SF,False,3098,3232,70,93,2,1,3,False,"[{'type': 'rush', 'distance': 14, 'result': '(..."
350,2015,1,400791600,18,MIN,20,3,SF,False,3232,3425,80,38,0,7,0,False,"[{'type': 'k', 'distance': 45, 'result': 'B.Pi..."
351,2015,1,400791600,19,SF,20,3,SF,False,3425,3600,52,68,5,0,0,False,"[{'type': 'rush', 'distance': 3, 'result': '(2..."

In [ ]:
target = drives_df[drives_df['gameId'] == '401671766']

target[['position', 'winning', 'startTime', 'stopTime']]

       position winning  startTime  stopTime
54909         1    None          0        91
54910         2     PHI         91       304
54911         3     PHI        304       401
54912         4     PHI        401       594
54913         5     PHI        594       647
54914         6    None        647       678
54915         7     PHI        678       827
54916         8     PHI        827       980
54917         9     PHI        980      1253
54918        10     PHI       1253      1646
54919        11     PHI       1646      1723
54920        12     PHI       1723      1763
54921        13     PHI       1763      1800
54922        14     PHI       1800      2228
54923        15     PHI       2228      2350
54924        16     PHI       2350      2743
54925        17     PHI       2743      2971
54926        18     PHI       2971      3600